exports.shortNames = {
    'AWHMAN':"Avg. Hours Worked",
    'ICSA':"Initial Claims",
    'ACDGNO':"New Orders Durables",
    'AMTMNO':"New Orders",
    'UNXANO':"New Orders Cap Goods",
    'PERMIT':"New Housing Units",
    'M1109BUSM293NNBR':"DJIA Return",
    'T10Y3M':"10yr / 3m Spread",
    'UMCSENT':"Consumer Sentiment",
    'PAYEMS':"Nonfarm Payrolls",
    'DSPIC96':"Disposable Income",
    'INDPRO':"Industrial Production",
    'CMRMTSPL':"Manufacturing Sales",
    'UEMPMEAN':"Avg. Time Out of Work",
    'ISRATIO':"Inventory to Sales Ratio",
    'ULCNFB':"Labor Cost",
    'MPRIME':"Prime Rate",
    'TOTCI':"Commercial Loans",
    'TDSP':"Debt Service to Income",
    'CUSR0000SAS':"CPI - Services",
    'USSLIND':"Leading Index for US",
    'CPIAUCSL':"CPI",
    'GDPC1':"Real GDP"
}
